set nocompatible
filetype off
set rtp+=$HOME/.vim/bundle/Vundle.vim/
call vundle#rc()

Plugin 'gmarik/vundle'
"Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'rainbow_parentheses.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'kien/ctrlp.vim'
"Bundle 'Align'
"Bundle 'Colour-Sampler-Pack'
"Bundle 'CSApprox'
"Bundle 'DirDiff.vim'
"Bundle 'ervandew/supertab'
"Bundle 'fugitive.vim'
" Bundle 'jQuery'
"Bundle 'matchit.zip'
" Bundle 'pangloss/vim-javascript'
"Bundle 'ruby-matchit'
"Bundle 'ScrollColors'
"Bundle 'surround.vim'
"Bundle 'Tabular'
"Bundle 'textobj-rubyblock'
"Bundle 'textobj-user'
"Bundle 'tpope/vim-rails.git'
"Bundle 'tpope/vim-eunuch.git'
"Bundle 'vim-coffee-script'
" Bundle 'DrawIt'
" Bundle 'Markdown'
" Bundle 'jgdavey/vim-turbux'
" Bundle 'jgdavey/tslime.vim'
"Bundle 'tpope/vim-endwise'
"Bundle 'tpope/vim-speeddating'
"Bundle 'tpope/vim-commentary'
"Bundle 'tpope/vim-haml'
"Bundle 'Solarized'
"Bundle 'scrooloose/nerdcommenter'
" Bundle 'nono/vim-handlebars'
"Bundle 'tpope/vim-dispatch'
"Bundle 'tpope/vim-markdown'
"Bundle 'Syntastic'
"Bundle 'fatih/vim-go'
"Bundle 'guns/vim-clojure-static'
"Bundle 'tpope/vim-fireplace'
"Plugin 'paredit.vim'
"Plugin 'jpalardy/vim-slime'
"let g:slime_target = "tmux"

filetype plugin indent on

let mapleader="\<Space>"

syntax on
set tabstop=2       " number of visual spaces per TAB
set softtabstop=2   " number of spaces in tab when editing
set expandtab       " tabs are spaces
set shiftwidth=2

set nowrap          " don't wrap lines

set number              " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
" hi MatchParen cterm=none ctermbg=grey ctermfg=black
" hi CursorLine cterm=NONE ctermbg=darkred ctermfg=white

set showmatch           " highlight matching [{()}]

set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" CtrlP settings
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0

set nobackup " Turn off swap files
set nowritebackup
set noswapfile

set autoread " Autoload files that have changed

function! NumberToggle()
  if(&relativenumber == 1)
    set norelativenumber
  else
    set relativenumber
  endif
endfunc

nnoremap <Bslash> :call NumberToggle()<cr>

set rnu
"au BufEnter * :set rnu
"au BufLeave * :set nu
"au WinEnter * :set rnu
"au WinLeave * :set nu
"au InsertEnter * :set nu
"au InsertLeave * :set rnu
"au FocusLost * :set nu
"au FocusGained * :set rnu

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

map <C-n> :NERDTreeToggle<CR>
